packages:
  - packages/*
onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
overrides:
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.2